export enum DeclineReasonTypeEnum {
  DUPLICATE_APPLICATION = 'DUPLICATE_APPLICATION',
  INVALID_HERO_PHOTO = 'INVALID_HERO_PHOTO',
  TYPO_IN_NAME = 'TYPO_IN_NAME',
  INCORRECT_LIFESPAN = 'INCORRECT_LIFESPAN',
  TERMS_VIOLATION = 'TERMS_VIOLATION',
  AUTO_MOD_GIGA = 'AUTO_MOD_GIGA',
  AUTO_MOD_VIZIER = 'AUTO_MOD_VIZIER',
}
